project_id = "beadflow-local"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/reset-password"]

[auth.email]
enable_confirmations = true
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage.vector]
enabled = false
